option_settings:
  aws:elasticbeanstalk:application:environment:
    APP_ENV: production
  aws:elasticbeanstalk:container:php:phpini:
    document_root: /
    memory_limit: 256M
  aws:elasticbeanstalk:environment:proxy:
    ProxyServer: apache
