name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, pdo, pdo_mysql

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Check if package.json exists
        id: check_files
        run: |
          if [ -f "package.json" ]; then
            echo "package_json_exists=true" >> $GITHUB_OUTPUT
          else
            echo "package_json_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Node.js
        if: steps.check_files.outputs.package_json_exists == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        if: steps.check_files.outputs.package_json_exists == 'true'
        run: npm install

      - name: Build assets
        if: steps.check_files.outputs.package_json_exists == 'true'
        run: npm run build

      - name: Prepare deployment package
        run: |
          # Create a clean directory for the deployment package
          mkdir -p deploy
          # Copy only necessary files
          cp -r api assets docs src styles tests vendor deploy/ 2>/dev/null || true
          cp .env.example aws_connection.php composer.json composer.lock db_connection.php db_init.php index.php render.yaml Procfile deploy/ 2>/dev/null || true
          # Copy .ebextensions if it exists
          if [ -d ".ebextensions" ]; then
            cp -r .ebextensions deploy/
          fi
          # Create the zip file
          cd deploy && zip -r ../app.zip . && cd ..

      - name: Validate deployment package
        run: |
          if [ ! -f app.zip ]; then
            echo "Deployment package not created"
            exit 1
          fi
          if [ $(stat -c%s app.zip) -lt 1000 ]; then
            echo "Deployment package is too small"
            exit 1
          fi

      - name: Log Environment Variables
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}"
          echo "AWS_REGION: ${{ secrets.AWS_REGION }}"

      - name: Validate Environment Variables
        run: |
          if [[ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]]; then echo "AWS_ACCESS_KEY_ID is not set"; exit 1; fi
          if [[ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]]; then echo "AWS_SECRET_ACCESS_KEY is not set"; exit 1; fi
          if [[ -z "${{ secrets.EB_ENVIRONMENT_NAME }}" ]]; then echo "EB_ENVIRONMENT_NAME is not set"; exit 1; fi
          if [[ -z "${{ secrets.AWS_REGION }}" ]]; then echo "AWS_REGION is not set"; exit 1; fi

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: battleships
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: v-${{ github.run_number }}-${{ github.sha }}-${{ github.event.head_commit.timestamp }}
          deployment_package: app.zip
          wait_for_deployment: true
